### ISSUE TITLE
fatal: could not read Password for 'https://***@github.com'

### ISSUE THREAD

**Issue by msche** [newrelic/wiki-sync-action#3]
When I try to sync my documentation to the wiki I get the following exception:

```
fatal: could not read Password for 'https://***@github.com': No such device or address
```

## Description

When I try to sync the documentation to the wiki for project https://github.com/UniKnow/jsoar I get the above exception. The default branch for the project is `maven` and wiki is enabled.

## Relevant Logs / Console output

See this build: https://github.com/UniKnow/jsoar/actions/runs/927556596

**Comment by msche** [comment]
Found reason for failure. The token I was using was not correct.

**Comment by kurnakovv** [comment]
It took me a few hours to figure this all out, so I'll leave this comment here :)

You can read about how to create token [here](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)
And select permissions: "Repository permissions" -> "Content"

![Image](https://github.com/user-attachments/assets/27e7060b-21e8-4295-835c-8c303802ede5)
